[[headers]]
  for = "/*.mp4"
  [headers.values]
    Content-Type = "video/mp4"
    Cache-Control = "public, max-age=31536000"

[build]
  publish = "."

[build.environment]
  NETLIFY_USE_YARN = "true"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[media]
  large_media = true 